language: python
python:
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -U pytest
  - pip install pytest-html

# command to run tests
script:
  - pytest --html=report.html

